case "$EBUILD_PHASE" in
    preinst )
        save_configure
        ;;
    * )
        :
        ;;
esac

# printf "\n EBUILD_PHASE=$EBUILD_PHASE : Package %s/%s (%s) \n\n" ${CATEGORY} ${PN} ${T}

save_configure () {
    grep -Ee '^(.*/)configure' "${T}/build.log" >"/var/log/emerge/${P}-configure.log"
    [[ ! -s "/var/log/emerge/${P}-configure.log" ]] && rm "/var/log/emerge/${P}-configure.log"
}
